/*
 * Asset Location Optimizer — core logic
 *
 * Principle: your overall stock/bond ratio is fixed by your risk tolerance.
 * Asset *location* decides WHICH account each dollar of stocks vs bonds lives
 * in. Because bond interest is taxed every year as ordinary income while
 * equities enjoy deferral, favorable qualified-dividend/LTCG rates, and a
 * basis step-up, the tax-efficient default is:
 *
 *   1. Fill TAX-DEFERRED accounts with bonds first (shelter ordinary income).
 *   2. Overflow bonds into TAX-FREE (Roth), then TAXABLE (ideally munis).
 *   3. Put equities in TAXABLE and TAX-FREE accounts.
 *   4. Any leftover tax-deferred space gets equities.
 *
 * The result keeps the SAME total bond % but concentrates bonds where their
 * interest is sheltered.
 */

const ACCOUNT_TYPES = {
  taxable: { label: "Taxable", className: "taxable" },
  deferred: { label: "Tax-deferred", className: "deferred" },
  free: { label: "Tax-free", className: "free" },
};

// Placement priority for bonds: tax-deferred → tax-free → taxable.
const BOND_PRIORITY = ["deferred", "free", "taxable"];
// Equities take whatever bonds don't: taxable → tax-free → tax-deferred.
const EQUITY_PRIORITY = ["taxable", "free", "deferred"];

/**
 * Compute the optimal asset location.
 *
 * @param {Array<{id, name, type, balance}>} accounts
 * @param {number} bondPct  target bond fraction of whole portfolio (0..1)
 * @returns {{accounts, totals, total, bondTarget, equityTarget, warnings}}
 */
function optimizeLocation(accounts, bondPct) {
  const valid = accounts.filter((a) => a.balance > 0);
  const total = valid.reduce((s, a) => s + a.balance, 0);

  const result = {
    accounts: [],
    total,
    bondTarget: total * bondPct,
    equityTarget: total * (1 - bondPct),
    warnings: [],
  };
  if (total <= 0) return result;

  // Remaining capacity (free space) in each account, and what we've placed.
  const placed = valid.map((a) => ({
    id: a.id,
    name: a.name,
    type: a.type,
    balance: a.balance,
    free: a.balance, // unallocated room
    bonds: 0,
    equities: 0,
  }));
  const byId = Object.fromEntries(placed.map((p) => [p.id, p]));

  let bondsLeft = result.bondTarget;
  let equitiesLeft = result.equityTarget;

  // --- Phase 1: place bonds by priority ---
  for (const type of BOND_PRIORITY) {
    if (bondsLeft <= 1e-9) break;
    for (const p of placed.filter((p) => p.type === type)) {
      if (bondsLeft <= 1e-9) break;
      const put = Math.min(p.free, bondsLeft);
      p.bonds += put;
      p.free -= put;
      bondsLeft -= put;
    }
  }

  // --- Phase 2: fill remaining space with equities by priority ---
  for (const type of EQUITY_PRIORITY) {
    if (equitiesLeft <= 1e-9) break;
    for (const p of placed.filter((p) => p.type === type)) {
      if (equitiesLeft <= 1e-9) break;
      const put = Math.min(p.free, equitiesLeft);
      p.equities += put;
      p.free -= put;
      equitiesLeft -= put;
    }
  }

  // --- Diagnostics ---
  const deferredSpace = placed
    .filter((p) => p.type === "deferred")
    .reduce((s, p) => s + p.balance, 0);
  if (result.bondTarget > deferredSpace + 1e-6) {
    const overflow = result.bondTarget - deferredSpace;
    const hasFree = placed.some((p) => p.type === "free");
    result.warnings.push(
      `Your bond target (${fmtMoney(result.bondTarget)}) exceeds your ` +
        `tax-deferred space (${fmtMoney(deferredSpace)}). ${fmtMoney(overflow)} ` +
        `of bonds had to spill into ${hasFree ? "Roth, then " : ""}taxable — ` +
        `consider tax-exempt municipal bonds for the taxable portion.`
    );
  }
  if (deferredSpace > result.bondTarget + 1e-6 && result.equityTarget > 0) {
    result.warnings.push(
      `You have more tax-deferred space than bonds, so the surplus holds ` +
        `equities. That's fine — bonds are fully sheltered.`
    );
  }

  result.accounts = placed;
  result.totals = {
    bonds: placed.reduce((s, p) => s + p.bonds, 0),
    equities: placed.reduce((s, p) => s + p.equities, 0),
  };
  return result;
}

/**
 * Estimate annual taxes for a given placement vs a naive "same mix in every
 * account" baseline. Only the taxable-account holdings generate current tax.
 *
 * @returns {{optimized:number, naive:number, savings:number}}
 */
function estimateTaxDrag(placed, accounts, bondPct, rates) {
  const { ordRate, qualRate, bondYield, eqYield } = rates;

  // Tax generated by the taxable account(s) under a given bond/equity split.
  const taxableTax = (bondDollars, equityDollars) =>
    bondDollars * bondYield * ordRate + // bond interest @ ordinary rate
    equityDollars * eqYield * qualRate; // dividends @ qualified rate

  // Optimized: use actual placement in taxable accounts.
  let optimized = 0;
  for (const p of placed.filter((a) => a.type === "taxable")) {
    optimized += taxableTax(p.bonds, p.equities);
  }

  // Naive baseline: every account (incl. taxable) holds the target mix.
  let naive = 0;
  for (const a of accounts.filter((a) => a.type === "taxable" && a.balance > 0)) {
    naive += taxableTax(a.balance * bondPct, a.balance * (1 - bondPct));
  }

  return { optimized, naive, savings: naive - optimized };
}

/* ---------- Currency ---------- */
// The app is built for a Philippine setting, so PHP is the default.
const CURRENCIES = {
  PHP: { code: "PHP", symbol: "₱", locale: "en-PH", label: "Philippine Peso" },
  USD: { code: "USD", symbol: "$", locale: "en-US", label: "US Dollar" },
  EUR: { code: "EUR", symbol: "€", locale: "de-DE", label: "Euro" },
  SGD: { code: "SGD", symbol: "S$", locale: "en-SG", label: "Singapore Dollar" },
  JPY: { code: "JPY", symbol: "¥", locale: "ja-JP", label: "Japanese Yen" },
};

let CURRENT_CURRENCY = "PHP";

function setCurrency(code) {
  if (CURRENCIES[code]) CURRENT_CURRENCY = code;
}
function currencySymbol() {
  return CURRENCIES[CURRENT_CURRENCY].symbol;
}

function fmtMoney(n) {
  const c = CURRENCIES[CURRENT_CURRENCY];
  return n.toLocaleString(c.locale, {
    style: "currency",
    currency: c.code,
    maximumFractionDigits: 0,
  });
}

function fmtPct(n) {
  return (n * 100).toFixed(0) + "%";
}

if (typeof module !== "undefined") {
  module.exports = {
    optimizeLocation,
    estimateTaxDrag,
    ACCOUNT_TYPES,
    CURRENCIES,
    setCurrency,
  };
}
